import { NextRequest, NextResponse } from "next/server";
import { getStorage } from "@/services/storage/storage-service";

// Public read surface for stored media (clinic logo/cover/gallery, doctor
// photo). The key is opaque and generated by the StorageService, so this
// streams bytes without exposing where they physically live. Cached hard —
// keys are content-addressable (a new upload = a new key), so the bytes behind
// a key never change.
export async function GET(_request: NextRequest, { params }: { params: Promise<{ key: string }> }) {
  const { key } = await params;
  const file = await getStorage().read(key);
  if (!file) return new NextResponse("Not found", { status: 404 });
  return new NextResponse(new Uint8Array(file.data), {
    headers: {
      "Content-Type": file.contentType,
      "Cache-Control": "public, max-age=31536000, immutable",
    },
  });
}
