import { notFound } from "next/navigation";
import prisma from "@/lib/prisma";
import PrintButton from "@/components/shared/print-button";

function ageFromDob(dob: Date | null): number | null {
  if (!dob) return null;
  return Math.floor((Date.now() - dob.getTime()) / (365.25 * 24 * 60 * 60 * 1000));
}

interface Vitals {
  bp: string;
  pulse: string;
  temp: string;
  spo2: string;
  weight: string;
}

function parseVitals(json: string | null | undefined): Vitals | null {
  if (!json) return null;
  try {
    return JSON.parse(json);
  } catch {
    return null;
  }
}

function formatDate(value: Date | string) {
  return new Date(value).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
}

export default async function VisitSummaryPrintPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const appointment = await prisma.appointment.findUnique({
    where: { id },
    include: { patient: true, doctor: true, clinic: true },
  });
  if (!appointment) notFound();

  const vitals = parseVitals(appointment.vitals_json);
  const age = ageFromDob(appointment.patient.date_of_birth);

  return (
    <div>
      <PrintButton />

      <header className="flex items-start justify-between border-b-2 border-black pb-4">
        <div>
          <h1 className="text-lg font-bold">Visit Summary</h1>
          <p className="text-[12px] text-muted-foreground">{appointment.clinic.name}</p>
        </div>
        <p className="text-[12px] text-muted-foreground">{formatDate(appointment.scheduled_time)}</p>
      </header>

      <section className="mt-4 grid grid-cols-2 gap-2 border-b border-border pb-4 text-[12px]">
        <div>
          <span className="font-semibold">Patient:</span> {appointment.patient.full_name}
          {age !== null ? ` · ${age} yrs` : ""}
          {appointment.patient.gender ? ` · ${appointment.patient.gender}` : ""}
        </div>
        <div className="text-right">
          <span className="font-semibold">Health ID:</span> {appointment.patient.health_id}
        </div>
        <div>
          <span className="font-semibold">Doctor:</span> {appointment.doctor.full_name}
          {appointment.doctor.specialty ? ` · ${appointment.doctor.specialty}` : ""}
        </div>
        <div className="text-right">
          <span className="font-semibold">Blood group:</span> {appointment.patient.blood_group}
        </div>
      </section>

      {appointment.chief_complaint && (
        <SummarySection title="Chief Complaint" body={appointment.chief_complaint} />
      )}
      {appointment.history_notes && (
        <SummarySection title="History" body={appointment.history_notes} />
      )}

      {vitals && (
        <section className="mt-4">
          <h2 className="text-[11px] font-bold tracking-wide uppercase text-muted-foreground">Vitals</h2>
          <div className="mt-1 grid grid-cols-5 gap-2 text-[12px]">
            <VitalTile label="BP" value={vitals.bp} />
            <VitalTile label="Pulse" value={vitals.pulse} />
            <VitalTile label="Temp" value={vitals.temp} />
            <VitalTile label="SpO2" value={vitals.spo2} />
            <VitalTile label="Weight" value={vitals.weight} />
          </div>
        </section>
      )}

      {appointment.diagnosis && <SummarySection title="Diagnosis" body={appointment.diagnosis} />}
      {appointment.prescription_notes && (
        <SummarySection title="Advice" body={appointment.prescription_notes} />
      )}
      {appointment.follow_up_date && (
        <SummarySection title="Follow-up" body={formatDate(appointment.follow_up_date)} />
      )}

      <footer className="mt-16 text-[11px] text-muted-foreground">
        Generated by Auriva — a record of this visit, not a prescription.
      </footer>
    </div>
  );
}

function SummarySection({ title, body }: { title: string; body: string }) {
  return (
    <section className="mt-4">
      <h2 className="text-[11px] font-bold tracking-wide uppercase text-muted-foreground">{title}</h2>
      <p className="mt-1 whitespace-pre-wrap">{body}</p>
    </section>
  );
}

function VitalTile({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded border border-border px-2 py-1.5 text-center">
      <p className="text-[10px] text-muted-foreground uppercase">{label}</p>
      <p className="font-medium">{value || "—"}</p>
    </div>
  );
}
